# This script creates a histogram of the average ln_gamma values generated by the Stan code

import pandas as pd
from matplotlib import pyplot as plt


def main():
    df = pd.read_csv('data.csv')  # Create a pandas dataframe from the vector data generated by the Stan code

    # Create and format the plot
    plt.clf()
    plt.figure(figsize=(20, 12))
    plt.hist(df['mean'], edgecolor='black')
    plt.subplot().set_title(r'Mean $ln(\gamma_{ij}^{\infty})$ Distribution', fontsize=32)
    plt.subplot().set_xlabel(r'$ln(\gamma_{ij}^{\infty})$', fontsize=24)
    plt.subplot().set_ylabel(r'$N$', fontsize=24)

    plt.savefig('mean-ln-gamma-distr.png')  # Save the plot to a png file


if __name__ == '__main__':
    main()
